import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./Layout.module.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sperax",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/", label: "Home" },
  { href: "https://docs.sperax.io/demeter-protocol", label: "Demeter" },
  { href: "https://docs.sperax.io/sperax-gauge", label: "Gauge" },
  { href: "https://docs.sperax.io/staking-protocol", label: "Stake" },
  { href: "https://docs.sperax.io/buyback-contract", label: "Buyback" },
  { href: "https://docs.sperax.io/sperax-gauge", label: "Swap" },
  { href: "https://docs.sperax.io/sperax-gauge", label: "More" },
];

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href="/global.css" />
      </head>
      <body>
        <div className={styles.container}>
          <nav className={styles.navbar}>
            <Link href="/">
              <Image src="/sperax.png" alt="My Image" width={150} height={50} />
            </Link>
            <div>
              {navLinks.map((link, index) => (
                <Link target="_blank" key={index} href={link.href}>
                  {link.label}
                </Link>
              ))}
            </div>
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
